#!/bin/bash
nomadctld="/usr/bin/ssh -p2222 yourserver"
if [ "$1" == "" ] || [ "$1" == "help" ]; then
        echo "commands:"
        echo -en "\\tps <filter> (shows all/filtered nomad jobs) (<filter> is optional)\\n"
        echo -en "\\tpsp <filter> (shows production nomad jobs) (<filter> is optional)\\n"
        echo -en "\\tpsq <filter> (shows quality nomad jobs) (<filter> is optional)\\n"
        echo -en "\\tpst <filter> (shows test nomad jobs) (<filter> is optional)\\n"
        echo -en "\\texec <execID> <command> (executes <command> in container <execID> (command default is /bin/sh)\\n"
        echo -en "\\tlogs <execID> (shows last 100 stdout lines of <execID>)\\n"
        echo -en "\\ttail <execID> (shows last 100 stdout lines of <execID> and keeps following them (like tail -f))\\n"
        echo -en "\\tstop <jobID> (stops a nomad job with <jobID> (<jobID> is the jobname))\\n"
        echo -en "\\tinspect <jobID> (inspects a nomad job with <jobID> (<jobID> is the jobname))\\n"
        echo -en "\\t\\n"
        exit
fi
if [[ "$1" =~ ^ps ]]; then
        $nomadctld "$1" "$2"
        exit
fi
if [ "$1" == "exec" ] || [ "$1" == "attach" ]; then
        if [ "$2" == "" ]; then
                echo "need: execID"
                exit
        fi
        $nomadctld -t "$@"
        exit
fi
if [ "$1" == "logs" ]; then
        if [ "$2" == "" ]; then
                echo "need: execID"
                exit
        fi
        $nomadctld "$1" "$2"
        exit
fi
if [ "$1" == "tail" ]; then
        if [ "$2" == "" ]; then
                echo "need: execID"
                exit
        fi
        $nomadctld "$1" "$2"
        exit
fi
if [ "$1" == "stop" ]; then
        if [ "$2" == "" ]; then
                echo "need: jobID"
                exit
        fi
        $nomadctld -t "$1" "$2"
        exit
fi
if [ "$1" == "inspect" ]; then
        if [ "$2" == "" ]; then
                echo "need: jobID"
                exit
        fi
        $nomadctld "$1" "$2"
        exit
fi
$nomadctld  "$@"
#echo Invalid command "$1". Please run nomadctl help for more information
